name: Tets

on:
  push:
    paths:
        - '.circleci/**.txt'
    branches-ignore:
        - 'master'
        - 'main'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check
        run: |
          . .github/workflows/test.sh